# Generated by Django 3.2.25 on 2024-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240711_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_for',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
